<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehiculo;
use App\Models\TipoActivo;
use App\Enums\EstadoVehiculo;

class VehiculosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener tipos de activos disponibles
        $vehiculoTipo = TipoActivo::where('nombre', 'Vehículo')->first();
        $maquinariaTipo = TipoActivo::where('nombre', 'Maquinaria')->first();

        // Crear vehículos de prueba
        $vehiculos = [
            // Camionetas
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Ford',
                'modelo' => 'F-150',
                'anio' => 2022,
                'n_serie' => 'FORD2022001',
                'placas' => 'ABC-123',
                'estatus' => EstadoVehiculo::DISPONIBLE,
                'kilometraje_actual' => 15000,
                'intervalo_km_motor' => 5000,
                'intervalo_km_transmision' => 60000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Ciudad de México',
                'municipio' => 'Miguel Hidalgo',
                'observaciones' => 'Camioneta en excelentes condiciones, ideal para trabajos de construcción.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Chevrolet',
                'modelo' => 'Silverado',
                'anio' => 2021,
                'n_serie' => 'CHEV2021001',
                'placas' => 'DEF-456',
                'estatus' => EstadoVehiculo::ASIGNADO,
                'kilometraje_actual' => 28000,
                'intervalo_km_motor' => 5000,
                'intervalo_km_transmision' => 60000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Estado de México',
                'municipio' => 'Naucalpan',
                'observaciones' => 'Vehículo asignado a proyecto de carreteras.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Toyota',
                'modelo' => 'Hilux',
                'anio' => 2023,
                'n_serie' => 'TOYO2023001',
                'placas' => 'GHI-789',
                'estatus' => EstadoVehiculo::DISPONIBLE,
                'kilometraje_actual' => 8500,
                'intervalo_km_motor' => 10000,
                'intervalo_km_transmision' => 100000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Jalisco',
                'municipio' => 'Guadalajara',
                'observaciones' => 'Pickup nueva, ideal para transporte de personal y herramientas.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Nissan',
                'modelo' => 'NP300',
                'anio' => 2020,
                'n_serie' => 'NISS2020001',
                'placas' => 'JKL-012',
                'estatus' => EstadoVehiculo::EN_MANTENIMIENTO,
                'kilometraje_actual' => 45000,
                'intervalo_km_motor' => 5000,
                'intervalo_km_transmision' => 80000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Nuevo León',
                'municipio' => 'Monterrey',
                'observaciones' => 'En mantenimiento preventivo, cambio de aceite y filtros.',
            ],

            // Camiones
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Freightliner',
                'modelo' => 'Cascadia',
                'anio' => 2019,
                'n_serie' => 'FREI2019001',
                'placas' => 'MNO-345',
                'estatus' => EstadoVehiculo::ASIGNADO,
                'kilometraje_actual' => 125000,
                'intervalo_km_motor' => 25000,
                'intervalo_km_transmision' => 160000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Veracruz',
                'municipio' => 'Veracruz',
                'observaciones' => 'Camión de carga pesada para transporte de maquinaria.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Volvo',
                'modelo' => 'FH16',
                'anio' => 2021,
                'n_serie' => 'VOLV2021001',
                'placas' => 'PQR-678',
                'estatus' => EstadoVehiculo::DISPONIBLE,
                'kilometraje_actual' => 75000,
                'intervalo_km_motor' => 30000,
                'intervalo_km_transmision' => 200000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Tamaulipas',
                'municipio' => 'Tampico',
                'observaciones' => 'Camión de alta capacidad, excelente para largas distancias.',
            ],

            // Maquinaria
            [
                'tipo_activo_id' => $maquinariaTipo?->id,
                'marca' => 'Caterpillar',
                'modelo' => '320D',
                'anio' => 2022,
                'n_serie' => 'CAT2022001',
                'placas' => 'STU-901',
                'estatus' => EstadoVehiculo::ASIGNADO,
                'kilometraje_actual' => null, // Maquinaria no tiene kilometraje
                'intervalo_km_motor' => null,
                'intervalo_km_transmision' => null,
                'intervalo_km_hidraulico' => 2000, // Horas de operación para hidráulico
                'estado' => 'Sonora',
                'municipio' => 'Hermosillo',
                'observaciones' => 'Excavadora en perfectas condiciones, ideal para excavaciones profundas.',
            ],
            [
                'tipo_activo_id' => $maquinariaTipo?->id,
                'marca' => 'Komatsu',
                'modelo' => 'PC210',
                'anio' => 2020,
                'n_serie' => 'KOMA2020001',
                'placas' => 'VWX-234',
                'estatus' => EstadoVehiculo::FUERA_DE_SERVICIO,
                'kilometraje_actual' => null,
                'intervalo_km_motor' => null,
                'intervalo_km_transmision' => null,
                'intervalo_km_hidraulico' => 1500,
                'estado' => 'Chihuahua',
                'municipio' => 'Chihuahua',
                'observaciones' => 'Requiere reparación mayor en sistema hidráulico.',
            ],
            [
                'tipo_activo_id' => $maquinariaTipo?->id,
                'marca' => 'John Deere',
                'modelo' => '350G',
                'anio' => 2023,
                'n_serie' => 'DEER2023001',
                'placas' => 'YZA-567',
                'estatus' => EstadoVehiculo::DISPONIBLE,
                'kilometraje_actual' => null,
                'intervalo_km_motor' => null,
                'intervalo_km_transmision' => null,
                'intervalo_km_hidraulico' => 2500,
                'estado' => 'Coahuila',
                'municipio' => 'Saltillo',
                'observaciones' => 'Excavadora nueva, lista para proyectos de construcción.',
            ],

            // Vehículos adicionales con diferentes marcas
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Mercedes-Benz',
                'modelo' => 'Actros',
                'anio' => 2021,
                'n_serie' => 'MERC2021001',
                'placas' => 'BCD-890',
                'estatus' => EstadoVehiculo::ASIGNADO,
                'kilometraje_actual' => 98000,
                'intervalo_km_motor' => 40000,
                'intervalo_km_transmision' => 250000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Puebla',
                'municipio' => 'Puebla',
                'observaciones' => 'Camión de carga europea, excelente rendimiento de combustible.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Isuzu',
                'modelo' => 'NPR',
                'anio' => 2022,
                'n_serie' => 'ISUZ2022001',
                'placas' => 'EFG-123',
                'estatus' => EstadoVehiculo::DISPONIBLE,
                'kilometraje_actual' => 22000,
                'intervalo_km_motor' => 10000,
                'intervalo_km_transmision' => 120000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Guanajuato',
                'municipio' => 'León',
                'observaciones' => 'Camión mediano ideal para entregas y transporte de materiales.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'RAM',
                'modelo' => '2500',
                'anio' => 2023,
                'n_serie' => 'RAM2023001',
                'placas' => 'HIJ-456',
                'estatus' => EstadoVehiculo::BAJA,
                'kilometraje_actual' => 180000,
                'intervalo_km_motor' => 8000,
                'intervalo_km_transmision' => 160000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Yucatán',
                'municipio' => 'Mérida',
                'observaciones' => 'Vehículo dado de baja por alto kilometraje y costos de mantenimiento.',
            ],

            // Vehículos con estado BAJA POR VENTA
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'GMC',
                'modelo' => 'Sierra',
                'anio' => 2018,
                'n_serie' => 'GMC2018001',
                'placas' => 'KLM-789',
                'estatus' => EstadoVehiculo::BAJA_POR_VENTA,
                'kilometraje_actual' => 145000,
                'intervalo_km_motor' => 8000,
                'intervalo_km_transmision' => 100000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Querétaro',
                'municipio' => 'Querétaro',
                'observaciones' => 'Vehículo vendido a tercero el 15/03/2025. Operación registrada con factura QRO-2025-045.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Dodge',
                'modelo' => 'Ram 1500',
                'anio' => 2017,
                'n_serie' => 'DODG2017001',
                'placas' => 'NOP-012',
                'estatus' => EstadoVehiculo::BAJA_POR_VENTA,
                'kilometraje_actual' => 165000,
                'intervalo_km_motor' => 5000,
                'intervalo_km_transmision' => 80000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Baja California',
                'municipio' => 'Tijuana',
                'observaciones' => 'Vendido en subasta pública. Precio de venta: $185,000 MXN. Fecha: 22/02/2025.',
            ],
            [
                'tipo_activo_id' => $maquinariaTipo?->id,
                'marca' => 'Case',
                'modelo' => '580N',
                'anio' => 2016,
                'n_serie' => 'CASE2016001',
                'placas' => null,
                'estatus' => EstadoVehiculo::BAJA_POR_VENTA,
                'kilometraje_actual' => null,
                'intervalo_km_motor' => null,
                'intervalo_km_transmision' => null,
                'intervalo_km_hidraulico' => 1000,
                'estado' => 'Sinaloa',
                'municipio' => 'Culiacán',
                'observaciones' => 'Retroexcavadora vendida a empresa de construcción local. Documentación de transferencia completa.',
            ],

            // Vehículos con estado BAJA POR PÉRDIDA
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Mitsubishi',
                'modelo' => 'L200',
                'anio' => 2020,
                'n_serie' => 'MITS2020001',
                'placas' => 'QRS-345',
                'estatus' => EstadoVehiculo::BAJA_POR_PERDIDA,
                'kilometraje_actual' => 52000,
                'intervalo_km_motor' => 10000,
                'intervalo_km_transmision' => 100000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Guerrero',
                'municipio' => 'Acapulco',
                'observaciones' => 'Vehículo robado el 10/01/2025. Denuncia ministerial: GUER-2025-00124. Aseguradora notificada.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Mazda',
                'modelo' => 'BT-50',
                'anio' => 2019,
                'n_serie' => 'MAZD2019001',
                'placas' => 'TUV-678',
                'estatus' => EstadoVehiculo::BAJA_POR_PERDIDA,
                'kilometraje_actual' => 78000,
                'intervalo_km_motor' => 10000,
                'intervalo_km_transmision' => 120000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Michoacán',
                'municipio' => 'Morelia',
                'observaciones' => 'Pérdida total por accidente en carretera el 05/02/2025. Dictamen de perito incluido.',
            ],
            [
                'tipo_activo_id' => $maquinariaTipo?->id,
                'marca' => 'Bobcat',
                'modelo' => 'S650',
                'anio' => 2021,
                'n_serie' => 'BOBC2021001',
                'placas' => null,
                'estatus' => EstadoVehiculo::BAJA_POR_PERDIDA,
                'kilometraje_actual' => null,
                'intervalo_km_motor' => null,
                'intervalo_km_transmision' => null,
                'intervalo_km_hidraulico' => 500,
                'estado' => 'Oaxaca',
                'municipio' => 'Oaxaca de Juárez',
                'observaciones' => 'Minicargador extraviado en obra. Reporte de pérdida presentado el 18/03/2025.',
            ],

            // Vehículos adicionales con diferentes estados para pruebas
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Hino',
                'modelo' => '500 Series',
                'anio' => 2022,
                'n_serie' => 'HINO2022001',
                'placas' => 'WXY-901',
                'estatus' => EstadoVehiculo::DISPONIBLE,
                'kilometraje_actual' => 32000,
                'intervalo_km_motor' => 20000,
                'intervalo_km_transmision' => 150000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'Aguascalientes',
                'municipio' => 'Aguascalientes',
                'observaciones' => 'Camión mediano en excelente estado, recién liberado de obra anterior.',
            ],
            [
                'tipo_activo_id' => $vehiculoTipo?->id,
                'marca' => 'Kenworth',
                'modelo' => 'T680',
                'anio' => 2021,
                'n_serie' => 'KENW2021001',
                'placas' => 'ZAB-234',
                'estatus' => EstadoVehiculo::ASIGNADO,
                'kilometraje_actual' => 89000,
                'intervalo_km_motor' => 25000,
                'intervalo_km_transmision' => 200000,
                'intervalo_km_hidraulico' => null,
                'estado' => 'San Luis Potosí',
                'municipio' => 'San Luis Potosí',
                'observaciones' => 'Tractocamión asignado a ruta larga distancia, proyecto carretera federal.',
            ],
            [
                'tipo_activo_id' => $maquinariaTipo?->id,
                'marca' => 'Hyundai',
                'modelo' => 'HL960',
                'anio' => 2023,
                'n_serie' => 'HYUN2023001',
                'placas' => null,
                'estatus' => EstadoVehiculo::EN_MANTENIMIENTO,
                'kilometraje_actual' => null,
                'intervalo_km_motor' => null,
                'intervalo_km_transmision' => null,
                'intervalo_km_hidraulico' => 3000,
                'estado' => 'Durango',
                'municipio' => 'Durango',
                'observaciones' => 'Cargador frontal en servicio preventivo, revisión de sistemas hidráulicos.',
            ],
            [
                'tipo_activo_id' => $maquinariaTipo?->id,
                'marca' => 'JCB',
                'modelo' => '3CX',
                'anio' => 2018,
                'n_serie' => 'JCB2018001',
                'placas' => null,
                'estatus' => EstadoVehiculo::FUERA_DE_SERVICIO,
                'kilometraje_actual' => null,
                'intervalo_km_motor' => null,
                'intervalo_km_transmision' => null,
                'intervalo_km_hidraulico' => 1200,
                'estado' => 'Zacatecas',
                'municipio' => 'Zacatecas',
                'observaciones' => 'Retroexcavadora fuera de servicio por daño en motor. En espera de refacciones.',
            ],
        ];

        // Crear los vehículos
        foreach ($vehiculos as $vehiculoData) {
            try {
                Vehiculo::create($vehiculoData);
                $this->command->info("Vehículo creado: {$vehiculoData['marca']} {$vehiculoData['modelo']} - {$vehiculoData['placas']}");
            } catch (\Exception $e) {
                $this->command->error("Error creando vehículo {$vehiculoData['marca']} {$vehiculoData['modelo']}: " . $e->getMessage());
            }
        }

        $this->command->info('Seeder de vehículos completado exitosamente.');
    }
}